name: Test

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Test with Maven
        run: mvn test

      - name: Test Failed
        if: ${{ failure() }}
        uses: LeoCpii/discord-webhook-alert@master
        with:
          message: "Tests Failed"
          webhookUrl: ${{ secrets.DEPLOY_WEBHOOK }}
          type: error
